---
- name: Gather Log Files from {{ reporting_host }}
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Information Message
    ansible.builtin.debug:
      msg: "Attempting to Gather Logs from {{ reporting_host }}"
      
  - name: Download log file
    ansible.builtin.fetch:
      src: /var/log/dnf.log
      dest: /tmp